LOAN approval Status

In [48]:
# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

from sklearn.svm import SVC

from sklearn.neighbors import KNeighborsClassifier


data = pd.read_csv("C:/Users/msjka/Downloads/Data.csv")
data.head()

,Age,Income,Experience,LoanAmount,InterestRate,CreditHistoryLength,CreditScore,LoanApprovalStatus
0,24,80145,1,25000.0,9.91,2,636.0,Yes
1,22,80303,0,25000.0,13.06,3,554.0,Yes
2,22,241048,0,9000.0,6.17,4,587.0,No
3,144,241424,121,6000.0,11.86,2,807.0,No
4,25,241005,4,18000.0,16.32,3,708.0,No

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  20000 non-null  int64
 1   Income               20000 non-null  int64
 2   Experience           20000 non-null  int64
 3   LoanAmount           19999 non-null  float64
 4   InterestRate         20000 non-null  float64
 5   CreditHistoryLength  20000 non-null  int64
 6   CreditScore          19999 non-null  float64
 7   LoanApprovalStatus   20000 non-null  object
dtypes: float64(3), int64(4), object(1)
memory usage: 1.2+ MB

In [50]:
data.isnull().sum()

Age                    0
Income                 0
Experience             0
LoanAmount             1
InterestRate           0
CreditHistoryLength    0
CreditScore            1
LoanApprovalStatus     0
dtype: int64

In [51]:
data =  data.dropna()
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19998 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  19998 non-null  int64
 1   Income               19998 non-null  int64
 2   Experience           19998 non-null  int64
 3   LoanAmount           19998 non-null  float64
 4   InterestRate         19998 non-null  float64
 5   CreditHistoryLength  19998 non-null  int64
 6   CreditScore          19998 non-null  float64
 7   LoanApprovalStatus   19998 non-null  object
dtypes: float64(3), int64(4), object(1)
memory usage: 1.4+ MB

In [52]:
print(data.shape)

(19998, 8)

In [53]:
data.head()

,Age,Income,Experience,LoanAmount,InterestRate,CreditHistoryLength,CreditScore,LoanApprovalStatus
0,24,80145,1,25000.0,9.91,2,636.0,Yes
1,22,80303,0,25000.0,13.06,3,554.0,Yes
2,22,241048,0,9000.0,6.17,4,587.0,No
3,144,241424,121,6000.0,11.86,2,807.0,No
4,25,241005,4,18000.0,16.32,3,708.0,No

In [54]:
#convert LoanApprovalStatus into numerical values
data['LoanApprovalStatus'] = data ['LoanApprovalStatus'].astype('category')
data['LoanApprovalStatus'] = data ['LoanApprovalStatus'].cat.codes
data

,Age,Income,Experience,LoanAmount,InterestRate,CreditHistoryLength,CreditScore,LoanApprovalStatus
0,24,80145,1,25000.0,9.91,2,636.0,1
1,22,80303,0,25000.0,13.06,3,554.0,1
2,22,241048,0,9000.0,6.17,4,587.0,0
3,144,241424,121,6000.0,11.86,2,807.0,0
4,25,241005,4,18000.0,16.32,3,708.0,0
...,...,...,...,...,...,...,...,...
19995,29,50154,7,3200.0,14.22,10,605.0,0
19996,28,49869,8,5000.0,6.76,10,647.0,0
19997,29,50107,7,2000.0,7.74,8,607.0,0
19998,30,59584,12,4800.0,13.79,9,670.0,0
19999,27,60018,3,4800.0,14.65,7,676.0,0

Split data into dependent and independent variables

In [55]:
x = data.drop(['LoanApprovalStatus'],axis = 1)
x.head()

,Age,Income,Experience,LoanAmount,InterestRate,CreditHistoryLength,CreditScore
0,24,80145,1,25000.0,9.91,2,636.0
1,22,80303,0,25000.0,13.06,3,554.0
2,22,241048,0,9000.0,6.17,4,587.0
3,144,241424,121,6000.0,11.86,2,807.0
4,25,241005,4,18000.0,16.32,3,708.0

In [56]:
y = data [['LoanApprovalStatus']]
y.head()

   LoanApprovalStatus
0                   1
1                   1
2                   0
3                   0
4                   0

split data into training and testing data

In [57]:
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size = 0.3,random_state = 21)

In [58]:
x_train

,Age,Income,Experience,LoanAmount,InterestRate,CreditHistoryLength,CreditScore
39,26,24297,3,4000.0,7.51,4,678.0
13654,24,120709,4,25000.0,11.01,3,681.0
10586,23,58561,0,10000.0,12.84,4,619.0
11701,25,96986,2,10000.0,7.49,4,705.0
18492,33,37281,11,5000.0,11.01,9,677.0
...,...,...,...,...,...,...,...
16434,24,114781,1,4000.0,7.90,4,642.0
8965,24,75189,2,20000.0,16.70,2,653.0
5945,22,60755,0,6000.0,12.69,4,580.0
5328,23,41666,0,5500.0,13.47,2,616.0
15307,23,217249,2,5000.0,9.33,4,695.0

In [59]:
x_test

,Age,Income,Experience,LoanAmount,InterestRate,CreditHistoryLength,CreditScore
911,22,87469,0,1000.0,7.88,3,633.0
18328,27,29874,4,1450.0,11.01,9,690.0
7468,23,102685,1,7175.0,7.49,4,633.0
16004,22,55069,0,4000.0,11.01,3,642.0
12621,26,107335,2,10000.0,11.36,3,537.0
...,...,...,...,...,...,...,...
6053,22,54182,0,6400.0,15.99,2,666.0
9156,23,72742,0,8400.0,7.49,3,614.0
17927,28,113397,5,20000.0,14.26,9,669.0
234,22,26902,4,1400.0,11.01,2,653.0
3325,26,40039,2,4200.0,16.02,3,587.0

In [60]:
#Standardizing the data
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test) 
x_train_scaled

array([[ 0.55206853, -1.06841219,  0.1991863 , ..., -1.14357886,
         0.22053114,  1.01172432],
       [-0.17317714,  1.05680228,  0.54950793, ...,  0.0045037 ,
        -0.33042279,  1.07223248],
       [-0.53579998, -0.31312915, -0.85177859, ...,  0.60478687,
         0.22053114, -0.17826955],
       ...,
       [-0.89842282, -0.2647667 , -0.85177859, ...,  0.55558333,
         0.22053114, -0.96487567],
       [-0.53579998, -0.68554647, -0.85177859, ...,  0.81144173,
        -0.88137672, -0.23877771],
       [-0.53579998,  3.18483827, -0.15113533, ..., -0.54657592,
         0.22053114,  1.35460391]])

Models : Logistic Regression, Support Vector Machines (SVM), and K-Nearest Neighbor (KNN)

1. Logistic Regression

In [61]:
#Logistic regression
Model1 = LogisticRegression(random_state = 21)
Model1 = Model1.fit(x_train_scaled,y_train)
y_pred = Model1.predict(x_test_scaled)

C:\Users\msjka\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [62]:
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy Score is", round(accuracy*100),"%")

Accuracy Score is 82 %

In [63]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.96      0.89      4617
           1       0.71      0.34      0.46      1383

    accuracy                           0.82      6000
   macro avg       0.77      0.65      0.68      6000
weighted avg       0.80      0.82      0.79      6000

2. Support Vector Machines(SVM)

In [64]:
#Support Vector Machines
Model2 = SVC(kernel='linear')
Model2 = Model2.fit(x_train_scaled,y_train)
y_pred = Model2.predict(x_test_scaled)

C:\Users\msjka\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [65]:
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy Score is", round(accuracy*100),"%")

Accuracy Score is 77 %

In [66]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.77      1.00      0.87      4617
           1       0.00      0.00      0.00      1383

    accuracy                           0.77      6000
   macro avg       0.38      0.50      0.43      6000
weighted avg       0.59      0.77      0.67      6000

C:\Users\msjka\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\msjka\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\msjka\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

3. K-Nearest Neighbor (KNN)

In [67]:
Model3 = KNeighborsClassifier(n_neighbors=5)
Model3 = Model3.fit(x_train_scaled,y_train)
y_pred = Model3.predict(x_test_scaled)

C:\Users\msjka\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

In [68]:
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy Score is", round(accuracy*100),"%")

Accuracy Score is 80 %

In [69]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.93      0.88      4617
           1       0.60      0.36      0.45      1383

    accuracy                           0.80      6000
   macro avg       0.72      0.65      0.66      6000
weighted avg       0.78      0.80      0.78      6000